### ISSUE TITLE
no posters display

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#12]
f12 console output
![image](https://user-images.githubusercontent.com/72405030/193223424-62814c74-f727-4489-8603-f372b681b7e2.png)

i am just stuck on 
![image](https://user-images.githubusercontent.com/72405030/193223547-62a9227a-9a8c-41d5-a849-e25364bf6401.png)

also im running on unraid with docker pulling from emby.
and does the sync posters sync what is in jellyfin/emby. or do i need to add each poster for them to show up.

**Comment by newelement** [comment]
The first console error is because the websocket server does not seem to be running. I'm not sure what access you have, but you can start it by going into /socketserver and either using pm2 or node:

`pm2 start server.js` OR `node server.js` 

I see another error regarding the random poster order which I have not tested in a while, shame on me. I will get that resolved soon.

The reload posters action will not work without the websocket server running.

**Comment by binarygeek119** [comment]
when i run it i got this "[PM2][ERROR] Script already launched, add -f option to force re-execution"
so i ran it with "pm2 start server.js -f"

![image](https://user-images.githubusercontent.com/72405030/193376481-274031b1-6683-47e7-8491-a05e85ddac8c.png)

**Comment by binarygeek119** [comment]
im seeing this error after running above command
![image](https://user-images.githubusercontent.com/72405030/193391056-bfd0aad7-988f-465c-8fee-4d7f2083242b.png)

**Comment by binarygeek119** [comment]
also i was wanting to know about update dmp do i just click it or are there steps for updating before clicking?

**Comment by binarygeek119** [comment]
i figure it out it was because of the random setting
