### ISSUE TITLE
jellyfin posters pull

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#15]
i setup a jellyfin docker to test with.
i can get now playing to work. but does not show the poster thats playing.
i also cant get it to pull posters from jellyfin.

when play a movie that is not listed under posters
![image](https://user-images.githubusercontent.com/72405030/193408219-fbbde5bf-4cba-4056-8dea-43ed346cb913.png)
console
![image](https://user-images.githubusercontent.com/72405030/193408235-133b7402-b746-40ce-8b8c-9d0c2202cf9d.png)

when playing a movie that is listed in posters
![image](https://user-images.githubusercontent.com/72405030/193408298-1514791f-dbcd-45fe-b9a4-e9cc0845026f.png)
console
![image](https://user-images.githubusercontent.com/72405030/193408306-7b154381-f74c-44ba-a553-c7e45984afb0.png)

when syncing posters
![image](https://user-images.githubusercontent.com/72405030/193408360-aabfa138-0bc1-4554-b90e-94384b40e855.png)

**Comment by newelement** [comment]
Ugh, so Jellyfin had a pull request merged in here: [https://github.com/jellyfin/jellyfin/pull/7965](Jellyfin Github). That merge was to allow getting posters using an API key from Jellyfin instead of authenticating with a user account. It seems that merge has not been tagged for a release yet. I thought they already did. I tested the functionality/code with user authentication, but would rather use API key as I have it setup now.

 I will retest the now playing functionality as that was working with an API key.

**Comment by newelement** [comment]
This will stay open until they tag that merge with a release. I keep checking on it regularly.

**Comment by newelement** [comment]
I asked them when the fix will be tagged for release. Hopefully they will answer.

**Comment by newelement** [comment]
Who knows when they will tag this for release...
